name: Deploy Fabric Accelerator
on: workflow_dispatch 
env:
  WORKSPACE_NAME: testws
  FABRIC_CAPACITY_NAME: bafabric014e4fwwm2ufole
  WORKSPACE_ADMIN_ID: aca94643-2e36-4cd6-ba96-bfc513b37851
  WORKSPACE_COLLABORATOR_ID: 01e16ca5-e5da-49f3-ac27-a46f1cc68ede
  FABRIC_SQL_DB_NAME: controldb-test
jobs:
  deploy-fabric-accelerator:
    runs-on: ubuntu-latest
    env:
      FSQL_SERVER: null
      FSQL_DATABASE: null
    steps:

        # Checkout code
        - uses: actions/checkout@v3   

        # Python Version Pre-Requisites
        - name: Fabric CLI Python Pre-Requisites
          uses: actions/setup-python@v4
          with:
            python-version: 3.12
       
       # Install Fabric CLI 
        - name: Install Fabric CLI
          run: pip install ms-fabric-cli

       # Authenticate using Service Principal
        - name: Authenticate to Fabric
          run: |
            fab config set encryption_fallback_enabled true
            fab auth login -u ${{ secrets.ACTION_SPN_CLIENTID }} -p ${{ secrets.ACTION_SPN_SECRET }} --tenant ${{ secrets.TENANT_ID }} 

       # Create Workspace if it does not exist
        - name: Create Workspace if it does not exist
          run: |
            WorkspaceExists=$(fab exists $WORKSPACE_NAME.Workspace | tr -d '[:space:]')
            echo "WorkspaceExists: $WorkspaceExists"
            if [ "$WorkspaceExists" != "*true" ]; then
              fab create $WORKSPACE_NAME.Workspace -P capacityName=$FABRIC_CAPACITY_NAME
              fab acl set $WORKSPACE_NAME.Workspace -I $WORKSPACE_ADMIN_ID -R admin -f
              fab acl set $WORKSPACE_NAME.Workspace -I $WORKSPACE_COLLABORATOR_ID -R contributor -f
            fi 

       # Create Fabric SQL database if it does not exist
        - name: Create FSQL DB if it does not exist
          run: |
              FSQLExists=$(fab exists $WORKSPACE_NAME.Workspace/$FABRIC_SQL_DB_NAME.SQLDatabase | tr -d '[:space:]')
              echo "FSQLExists: $FSQLExists"
              if [ "$FSQLExists" != "*true" ]; then
                fab create $WORKSPACE_NAME.Workspace/$FABRIC_SQL_DB_NAME.SQLDatabase
              fi 
       # Create Fabric SQL database connection if it does not exist
        - name: Create FSQL DB Connection if it does not exist
          run: |
              set -x
              FSQLConnExists=$(fab exists .connections/"${WORKSPACE_NAME}-${FABRIC_SQL_DB_NAME}".Connection | tr -d '[:space:]')
              echo "FSQLConnExists: $FSQLConnExists"
              if [ "$FSQLConnExists" != "*true" ]; then
                server=$(fab get $WORKSPACE_NAME.Workspace/$FABRIC_SQL_DB_NAME.SQLDatabase -q properties.serverFqdn| tr -d '\r')
                database=$(fab get $WORKSPACE_NAME.Workspace/$FABRIC_SQL_DB_NAME.SQLDatabase -q properties.databaseName| tr -d '\r') 
                FSQL_SERVER=$server
                FSQL_DATABASE=$database
                echo "Creating connection for server: $FSQL_SERVER and database: $FSQL_DATABASE"
                fab create .connections/"${WORKSPACE_NAME}-${FABRIC_SQL_DB_NAME}".Connection -P connectionDetails.creationMethod=SQL,connectionDetails.type=SQL,connectionDetails.parameters.server=$FSQL_SERVER,connectionDetails.parameters.database=$FSQL_DATABASE,credentialDetails.type=ServicePrincipal,credentialDetails.servicePrincipalClientId=${{ secrets.ACTION_SPN_CLIENTID }},credentialDetails.servicePrincipalSecret=${{ secrets.ACTION_SPN_SECRET }},credentialDetails.tenantid=${{ secrets.TENANT_ID }} 
              fi
              set +x